redbus/urls.py
from django.contrib import admin
from django.urls import path, include

from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('redbusapp.urls')),
    # path('api-auth/', include('rest_framework.urls'))
]
from django.conf import settings

""" if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
                      path('__debug__/', include(debug_toolbar.urls)),
                  ] + urlpatterns
 """

redbusapp/urls.py
from django.urls import path

from .views.auth import*
from .views.journey import *
from .views.admin import *

app_name = "redbus"

urlpatterns = [
    path('register/', SignupUser.as_view(), name='register'),
    path('login/', LoginUser.as_view(), name='login'),
    path('logout/', LogoutUser, name='logout'),
    path('forgot/',Prereset.as_view(),name='stage1'),
    path('forgot/reset',reset.as_view(),name='stage2'),
    path('reset',changepass.as_view(),name='reset'),
    path('bus/',Get_Journey.as_view(),name='journey'),
    path('add/',admin_add_bus.as_view(),name='add_bus'),
    path('add/<int:pk>/route',admin_add_route.as_view(),name='add_route'),
    path('buses/',Get_buses.as_view(),name='buses'),
    path('seats/',Get_seats.as_view(),name='seats'),
    path('details/',get_details.as_view(),name='details'),
    path('confirmed/',get_ticket.as_view(),name='confirmation'),
    path('booking/',get_bookings.as_view(),name='booking'),
]

redbusapp/forms.py
from django import forms
from django.utils import timezone

from redbusapp.models import *


class addBus(forms.ModelForm):
    class Meta:
        model = Bus
        exclude = ['total_seats']
        widgets = {
            'number': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter license number'}),
            'company': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter company'}),
            'rows': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter seat rows'}),
            'columns': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Enter seat columns'}),
        }


class addRoute(forms.ModelForm):
    class Meta:
        model = Route
        exclude = ['bus']
        widgets = {
            'time': forms.TimeInput(attrs={'class': 'form-control', 'placeholder': 'Enter time'}, format='%h:%m'),
            'City': forms.ModelChoiceField(to_field_name='location', queryset=City.objects.all()),
            'price': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Enter price'}),
        }


class JourneyForm(forms.Form):
    source = forms.ModelChoiceField(
        queryset=City.objects.all()
    )
    destination = forms.ModelChoiceField(
        queryset=City.objects.all()
    )
    journey_date = forms.DateField(
        widget=forms.SelectDateWidget(), label='Joining Date', initial=timezone.now()
    )


class BusForm(forms.Form):
    bus = forms.IntegerField(
        widget=forms.HiddenInput()
    )


class Preforget(forms.Form):
    email = forms.EmailField(
        widget=forms.EmailInput(attrs={'placeholder': 'Enter your email', 'class': 'form-control'})
    )


class PostForget(forms.Form):
    security_code = forms.CharField(
        widget=forms.TextInput(attrs={'placeholder': 'Enter security code', 'class': 'form-control'})
    )


class resetpass(forms.Form):
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={'placeholder': 'Enter password', 'class': 'form-control form-change'})
    )
    confirm_password = forms.CharField(
        widget=forms.PasswordInput(attrs={'placeholder': 'Enter password again', 'class': 'form-control form-change'})
    )


class SeatsForm(forms.Form):
    seats = forms.CharField(
        widget=forms.HiddenInput(), max_length=100
    )


class SeatForm(forms.Form):
    seat = forms.CharField(
        max_length=2,
        widget=forms.HiddenInput()
    )
    row = forms.CharField(
        max_length=1, widget=forms.HiddenInput()
    )
    column = forms.IntegerField(
        widget=forms.HiddenInput()
    )
    Name = forms.CharField(
        max_length=100,
        widget=forms.TextInput(attrs={'placeholder': 'Enter name'})
    )
    Age = forms.IntegerField(
        min_value=0,
        max_value=150,
        widget=forms.NumberInput(attrs={'placeholder': 'Enter Age'})
    )
    gender = forms.ChoiceField(
        choices=((1, "Male"),
                 (2, "Female")),

    )


class ContactForm(forms.Form):
    Name = forms.CharField(
        max_length=100
    )
    Email = forms.EmailField()
    Mobile = forms.CharField(
        max_length=10
    )


class SignupForm(forms.Form):
    first_name = forms.CharField(
        max_length=75,
        required=True,
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter First Name'})
    )
    last_name = forms.CharField(
        max_length=75,
        required=True,
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter Last Name'})
    )
    username = forms.CharField(
        max_length=75,
        required=True,
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter User Name'})
    )
    email = forms.EmailField(
        required=True,
        widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Enter email'})
    )
    password = forms.CharField(
        max_length=75,
        required=True,
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Enter Password'})
    )


class ProfileForm(forms.Form):
    phone = forms.CharField(
        max_length=10,
        required=True,
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter Phone'})
    )


class LoginForm(forms.Form):
    username = forms.CharField(
        max_length=75,
        required=True,
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter User Name'})
    )
    password = forms.CharField(
        max_length=75,
        required=True,
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Enter Password'})
    )


class CancelForm(forms.Form):
    seats=forms.CharField(
        required=True,
        widget=forms.HiddenInput()
    )

redbusapp/views/admin.py
from django.views import View
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from django.views.generic import ListView, CreateView

from redbusapp.forms import addBus, addRoute
from redbusapp.models import Bus


class admin_add_bus(CreateView):
    template = 'add_bus.html'
    form_class = addBus

    def get(self, request, *args, **kwargs):
        form = addBus()
        return render(request, template_name='add_bus.html', context={'title': 'Add Bus', 'form': form})

    def post(self, request, *args, **kwargs):
        bus_form = addBus(request.POST)
        pk=0
        if bus_form.is_valid():
            bus = bus_form.save(commit=False)
            bus.total_seats = int(ord(request.POST['rows'].upper()) - 64) * int(request.POST['columns'])
            bus.save()
            pk=bus.id

        return redirect('redbus:add_route',pk=pk)


class admin_add_route(CreateView):
    template = 'add_route.html'
    form_class = addRoute

    def get(self, request, *args, **kwargs):
        form = addRoute()
        return render(request, template_name='add_route.html', context={'title': 'Add Route', 'form': form})

    def post(self, request, *args, **kwargs):
        route_form = addRoute(request.POST)
        if route_form.is_valid():
            bus = route_form.save(commit=False)
            bus.bus=Bus.objects.get(pk=kwargs.get('pk'))
            bus.save()

        return redirect('redbus:add_route',pk=kwargs.get('pk'))

redbusapp/views/journey.py
import datetime

from django.core.mail import send_mail
from django.utils import timezone

from django.shortcuts import render, redirect
from django.views.generic import ListView

from redbusapp.forms import JourneyForm, BusForm, SeatsForm, SeatForm, ContactForm
from redbusapp.models import Bus, Route, Ticket, Contact, Seats, source, City


class Get_Journey(ListView):
    template_name = 'journey.html'
    form_class = JourneyForm

    def get(self, request, *args, **kwargs):
        form = JourneyForm()
        return render(request, template_name='journey.html', context={'title': 'Select Journey', 'form': form})

    def post(self, request, *args, **kwargs):
        user_form = JourneyForm(request.POST)

        date, month, year = timezone.now().day, timezone.now().month, timezone.now().year
        hsh = date + month * 13 + year * 365
        cmp = int(request.POST['journey_date_day']) + (int(request.POST['journey_date_month']) * 13) + (
                int(request.POST['journey_date_year']) * 365)
        hsh2 = date + (month + 1) * 13 + year * 365
        if hsh <= cmp:
            if request.POST['source'] == request.POST['destination']:
                return render(request, 'journey.html',
                              {'form': user_form, 'error_message': 'Source and destination can\'t be the same'})
            elif cmp > hsh2:
                return render(request, 'journey.html',
                              {'form': user_form,
                               'error_message': 'Advance booking can be done only for a month duration'})
            else:
                request.session['source'] = request.POST['source']
                request.session['destination'] = request.POST['destination']
                request.session['journey_date_day'] = request.POST['journey_date_day']
                request.session['journey_date_month'] = request.POST['journey_date_month']
                request.session['journey_date_year'] = request.POST['journey_date_year']
                return redirect('redbus:buses')
        else:
            return render(request, 'journey.html', {'form': user_form, 'error_message': 'Not a Valid Date'})


class Get_buses(ListView):
    template_name = 'view_bus.html'

    def get_queryset(self):
        source = self.request.session.get('source')
        destination = self.request.session.get('destination')
        sday = self.request.session.get('journey_date_day')
        smonth = self.request.session.get('journey_date_month')
        syear = self.request.session.get('journey_date_year')
        date, month, year = timezone.now().day, timezone.now().month, timezone.now().year
        hsh = date + month * 13 + year * 365
        error = ""
        self.request.session['error'] = error
        cmp = int(sday) + int(smonth) * 13 + int(syear) * 365
        if hsh == cmp:
            flag = 1
            z = datetime.datetime.now() + datetime.timedelta(minutes=30)
            hsh = int(z.day) + (int(z.month) * 13) + (int(z.year) * 365)
            if hsh == cmp:
                routes_s = Route.objects.filter(location_id=source).filter(
                    time__gte=(z))
                routes_d = Route.objects.filter(location_id=destination).filter(
                    time__gte=z)
            else:
                error = "Showing Buses for tomorrow"
                self.request.session['error'] = error
                self.request.session['journey_date_day'] = z.day
                self.request.session['journey_date_month'] = z.month
                self.request.session['journey_date_year'] = z.year
                routes_s = Route.objects.filter(location_id=source)
                routes_d = Route.objects.filter(location_id=destination)
        else:
            routes_s = Route.objects.filter(location_id=source)
            routes_d = Route.objects.filter(location_id=destination)

        x = list(routes_s)
        y = list(routes_d)
        a = []
        for i in x:
            if {'bus_id': i.bus_id} in list(routes_d.values('bus_id')):
                m = Route.objects.filter(bus_id=i.bus_id).get(location_id=destination)
                if m.price - i.price > 0:
                    a.append(
                        {'bus_id': i.bus_id, 'bus_price': m.price - i.price, 'arrival': i.time, 'departure': m.time})
        return a

    def get(self, request, *args, **kwargs):
        a = self.get_queryset()
        user_form = JourneyForm()
        error = request.session['error']
        if a == []:
            error = "No buses Found"
            return redirect('redbus:journey')
        form = BusForm()
        return render(request, template_name='bus.html',
                      context={'title': 'Select Journey', 'form': form, 'buses': a, 'error': error})

    def post(self, request, *args, **kwargs):
        form = BusForm(request.POST)
        if form.is_valid():
            x = int(form['bus'].value())
            request.session['bus'] = x
            buses = self.get_queryset()
            for i in buses:
                if i['bus_id'] == int(x):
                    request.session['arrival'] = i['arrival'].strftime('%X')
                    request.session['depart'] = i['departure'].strftime('%X')
                    break
            return redirect('redbus:seats')
        else:
            return render(request, template_name='bus.html',
                          context={'title': 'Select Journey', 'error': 'Bus_form not valid'})


class Get_seats(ListView):
    template = 'view_bus.html'

    def get_queryset(self):
        bus_id = self.request.session.get('bus')
        source = self.request.session.get('source')
        destination = self.request.session.get('destination')
        sday = self.request.session.get('journey_date_day')
        smonth = self.request.session.get('journey_date_month')
        syear = self.request.session.get('journey_date_year')
        price = Route.objects.filter(bus_id=bus_id).get(location=destination).price - Route.objects.filter(
            bus_id=bus_id).get(location=source).price
        self.request.session['price'] = price
        cities = list(Route.objects.filter(bus_id=bus_id).values_list('location'))
        times = list(Route.objects.filter(bus_id=bus_id).values_list('time'))
        z = [x for _, x in sorted(zip(times, cities), key=lambda pair: pair[0])]
        bus1 = Bus.objects.get(pk=bus_id)
        seat = [0] * (ord(bus1.rows) - 64) * (bus1.columns)
        dest = 0
        src = 0
        for i in range(len(z)):
            if z[i][0] == int(source):
                src = i
            if z[i][0] == int(destination):
                dest = i
        i = 0
        seats = []
        while i != dest:
            for j in range(i + 1, len(z)):
                if j != src:
                    seats += Ticket.objects.filter(date__year=int(syear)).filter(date__month=int(smonth)).filter(
                        date__day=int(sday)).filter(
                        bus_id=int(bus_id)).filter(source__name_id=int(z[i][0])).filter(
                        destination_id=int(z[j][0])).values_list(
                        'seat__row', 'seat__column')
            i += 1
        # seats = Ticket.objects.filter(date__year=int(syear)).filter(date__month=int(smonth)).filter(
        #     date__day=int(sday)).filter(
        #     bus_id=int(bus_id)).filter(source__name_id=int(source)).filter(destination_id=int(destination)).values_list(
        #     'seat__row', 'seat__column')
        return seats, seat

    def get(self, request, *args, **kwargs):
        seats, seat = self.get_queryset()
        bus_id = self.request.session.get('bus')
        price = request.session.get('price')
        rows = Bus.objects.get(pk=bus_id).rows
        columns = Bus.objects.get(pk=bus_id).columns
        form = SeatsForm()
        x = [str(i[0]) + str(i[1]) for i in seats]
        request.session['seats'] = x
        return render(request, template_name='view_bus.html', context={
            'title': 'Select Seats',
            'seats': [str(i[0]) + str(i[1]) for i in seats],
            'rows': [chr(i) for i in range(ord('A'), ord(rows) + 1)],
            'columns': [i for i in range(1, columns + 1)],
            'form': form,
            'price': price
        })

    def post(self, request, *args, **kwargs):
        seats = SeatsForm(request.POST)
        if seats.is_valid():
            seat = seats['seats'].value().split(',')
            seat = seat[:-1]
            booked = request.session.get('seats')
            error = None
            bus_id = self.request.session.get('bus')
            price = request.session.get('price')
            rows = Bus.objects.get(pk=bus_id).rows
            columns = Bus.objects.get(pk=bus_id).columns
            form = SeatsForm()
            x = [str(i[0]) + str(i[1]) for i in seat]
            request.session['seats'] = x
            for i in seat:
                if i.casefold() in booked:
                    return render(request, template_name='view_bus.html', context={
                        'title': 'Select Seats',
                        'seats': x,
                        'rows': [chr(i) for i in range(ord('A'), ord(rows) + 1)],
                        'columns': [i for i in range(1, columns + 1)],
                        'form': form,
                        'price': price,
                        'error': "Can manually update the booked seats",
                    })
            else:
                request.session['book'] = seat
                return redirect('redbus:details')


class get_details(ListView):
    template_name = 'details.html'

    def get_queryset(self):
        pass

    def get(self, request, *args, **kwargs):
        seats_to_book = request.session.get('book')
        forms = []
        for i in seats_to_book:
            form = SeatForm()
            forms.append(form)
        contact = ContactForm()
        return render(request, template_name='details.html',

redbusapp/templates/add_route.html
{% extends "index.html" %}

{% block content %}
    <form action="{% url 'redbus:add_bus' %}">
        <button class="btn btn-default">Add Bus</button>
    </form>
    <br/>
    <form method="post">
        {% csrf_token %}
        {{ form }}
        <br/>
        <br/>
        <button type="submit" value="submit">Submit</button>
    </form>
    <br/>
{% endblock %}

redbusapp/templates/bus.html
{% extends "index.html" %}

{% block content %}

    <form method="post">
        {{ error }}
        {% csrf_token %}
        {{ form }}
        <table class="table-hover table-bordered">
            <thead>
            <th>Bus id</th>
            <th>Price</th>
            <th>Arrival Time</th>
            <th>Departure Time</th>
            <th>Book</th>
            </thead>
            {% for bus in buses %}
                <tr>
                    <td>{{ bus.bus_id }}</td>
                    <td>{{ bus.bus_price }}</td>
                    <td>{{ bus.arrival }}</td>
                    <td>{{ bus.departure }}</td>
                    <td>
                        <button class="mdl-button--colored" type="submit"
                                onclick="document.getElementById('id_bus').value='{{ bus.bus_id }}'">
                            Book
                        </button>
                    </td>
                </tr>
            {% endfor %}
        </table>
        <br/>
        <br/>
    </form>

{% endblock %}

redbusapp/templates/details.html
{% extends "index.html" %}
{% load redbusapp_extras %}
{% block content %}
	<h3>{{ error }}</h3>
	<form method="post">
		{% csrf_token %}
		<div class="card center-div">
			<label>Contact Details</label>
			<div>
				{{ contact.as_p }}
			</div>
		</div>
		<br>
		<br>
		<center><label><h4>Passenger Details</h4></label></center>
		{% for form in forms %}
			<div class="card center-div">
				<p>
					Seat :{% cycle_list seats %}
				</p>
				<div>
					{{ form.as_p }}
				</div>

			</div>
			<br><br>
		{% endfor %}
		<center>
			<button class="mdl-button--colored " type="submit">Submit</button>
		</center>
	</form>
{% endblock %}

redbusapp/templates/error.html
{% extends "index.html" %}
{% block content %}
    <i>{{ error_message }}</i>
{% endblock %}

redbusapp/templates/index2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Your Site</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <!--<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://code.getmdl.io/1.3.0/material.indigo-pink.min.css">
    <script defer src="https://code.getmdl.io/1.3.0/material.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
            integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
            crossorigin="anonymous"></script>-->
    <link rel="stylesheet" href="https://bootswatch.com/4/lux/bootstrap.min.css">
</head>

<body>
<br>
<br>
<div class="container-fluid">
    <h3><center><div style="align-content: center">
        {{ title }}
    </div></center></h3>
<br>
    <br>
    <div class="dashboard">
        {% block content %}{% endblock %}
    </div>
</div>

<footer>
    <p>&copy; Your Bus 2018</p>
</footer>
</body>
</html>

redbusapp/templates/journey.html
{% extends "index.html" %}

{% block content %}
    {{ error_message }}
<form action="" method="post">
    {% csrf_token %}
    <div class="form-group">
    {{form.as_p}}
    </div>
    <br/>
    <br/>
<button type="submit" value="submit">Submit</button>
</form>

{% endblock %}

redbusapp/templates/login.html
{% extends "index.html"%}

{% block content %}
<form method="post">
    {% csrf_token %}
    <h3>{{ error }}</h3>
    <br>
    {{form}}
    <br/>
    <button class= "btn btn-default" type="submit" value="submit">Submit</button>
	<br>
	<br>
    <a href="{% url 'redbus:register'%}" style="float: left">
        New User! Click to Register
    </a>
    <a href="{% url 'redbus:stage1'%}" style="float: right">
        Forgot Your Password?
    </a>

</form>

{% endblock %}

redbusapp/templates/preforget.html
{% extends "index.html" %}

{% block content %}
<form method="post">
    {% csrf_token %}
    <h3>{{ error }}</h3>
    <label>Enter the email associated with <b>Your bus</b> account</label>
    <br>
    {{form}}
    <br/>
    <br/>
    <button class= "btn btn-default" type="submit" value="submit">Submit</button>
    <a href="{% url 'redbus:login'%}" style="float: right">
        Login
    </a>
    <a href="{% url 'redbus:register'%}" style="float: right">
        Register
    </a>

</form>

{% endblock %}

redbusapp/templates/registration.html
{% extends "index.html" %}

{% block content %}
<form method="post">
    {% csrf_token %}
    <h3>{{ error }}</h3>
    <br>
    {{form}}
    {{ contact }}
    <br/>
    <button class= "btn btn-default" type="submit" value="submit" style="float: left">Submit</button>
    <a href="{% url 'redbus:login'%}" style="float: right">
        Registered Already? Press here to Login
    </a>
</form>

{% endblock %}

redbusapp/templates/reset.html
{% extends "index.html" %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        <h3>{{ error }}</h3>
        {% if proceed %}
        <label>Enter new password</label>
        <br>
        {{ form }}
        <br/>
        <br/>
        <button class="btn btn-default" id="button" type="submit" value="submit" >Submit</button>
        <a href="{% url 'redbus:login' %}" style="float: right">
            Login
        </a>
        <a href="{% url 'redbus:register' %}" style="float: right">
            Register
        </a>
            {% else %}
            <h1>Restricted Access</h1>
        {% endif %}
    </form>

{% endblock %}

redbusapp/templates/tempticket.html
{% extends "index.html" %}

{% block content %}
    <h2 align="center">Happy Journey</h2>
    <h5 align="center">
        Bus Number:{{ bus_no }}
        &nbsp;&nbsp;
        Journey Date: {{ date }}
        &nbsp;&nbsp;
        <br>
        Source: {{ source }}
        &nbsp;&nbsp;
        Arrival Time: {{ arrival }}
        &nbsp;&nbsp;
        <br>
        Destination: {{ dest }}
        &nbsp;&nbsp;
        Departure Time: {{ depart }}
    </h5>
    <br>
    <h4>
        <table align="center" border="1 px">
            <th>Name</th>
            <th>Age</th>
            <th>Sex</th>
            <th>Seat</th>

            {% for ticket in tickets %}
                <tr>
                    <td>{{ ticket.name }}</td>
                    <td>{{ ticket.age }}</td>
                    <td>{{ ticket.gender }}</td>
                    <td>{{ ticket.seat }}</td>
                </tr>
            {% endfor %}
        </table>
    </h4>
    <h5 align="center">
        Price: {{ price }}
    </h5>
{% endblock %}

redbusapp/templates/view_bus.html
{% extends "index.html" %}
{% load redbusapp_extras %}
{% block content %}
    <style type="text/css">
        #available {
            background-color: #4CAF50;
            border: none;
            color: white;
            padding: 10px 15px;
            text-align: center;
            text-decoration: none;
            display: inline-block;
            font-size: 16px;
        }

        #booked {
            background-color: red;
            border: none;
            color: white;
            padding: 10px 15px;
            text-align: center;
            text-decoration: none;
            display: inline-block;
            font-size: 16px;
        }

        #selected {
            background-color: blue;
            border: none;
            color: white;
            padding: 10px 15px;
            text-align: center;
            text-decoration: none;
            display: inline-block;
            font-size: 16px;
        }
    </style>
    <script type="text/javascript">
        function change(x, price) {
            if (x.id === "available") {
                document.getElementById("seatdiv").style.visibility = "visible";
                document.getElementById("pricediv").style.visibility = "visible";
                x.id = "selected";
                document.getElementById("seats").innerText = document.getElementById("seats").innerText + x.innerText + ",";
                document.getElementById("id_seats").value = document.getElementById("seats").innerText;
                document.getElementById("price").innerText = parseInt(document.getElementById("price").innerText, 10) + price;
            }
            else if (x.id === "selected") {
                x.id = "available";
                document.getElementById("seats").innerText = document.getElementById("seats").innerText.replace(x.innerText + ",", "");
                document.getElementById("id_seats").value = document.getElementById("seats").innerText;
                document.getElementById("price").innerText = parseInt(document.getElementById("price").innerText, 10) - price;
                if (document.getElementById("seats").innerText === "") {
                    document.getElementById("seatdiv").style.visibility = "hidden";
                }
                if (parseInt(document.getElementById("price").innerText, 10) === 0) {
                    document.getElementById("pricediv").style.visibility = "hidden";
                }
            }
        }


    </script>
    <table>
    {{ error }}
        {% for row in rows %}
            <tr>{% for col in columns %}
                <td>
                    {% with row|addstr:col|stringformat:"s" as seat %}
                        {% if seat in seats %}
                            <button type="button" disabled="disabled" id="booked">{{ row }}{{ col }}</button>
                        {% else %}
                            <button type="button" onclick="change(this,{{ price }})" id="available">
                                {{ row }}{{ col }}</button>
                            </td>
                        {% endif %}
                    {% endwith %}
            {% endfor %}
            </tr>
        {% endfor %}
    </table>
    <br>
    &nbsp;&nbsp;
    <buttton type="button" disabled id="available"></buttton><label>&nbsp;&nbsp; Available</label>
    <buttton type="button" disabled id="booked"></buttton><label>&nbsp;&nbsp;Booked</label>
    <buttton type="button" disabled id="selected"></buttton><label>&nbsp;&nbsp;Selected</label>
    <div style="visibility: hidden" id="seatdiv">Selected seats:<p id="seats"></p><br></div>

    <div style="visibility: hidden;" id="pricediv">Price:<p id="price">0</p></div>
    <form method="post">
        {% csrf_token %}
        {{ form }}
        <button type="submit" class="mdl-button--colored">Book</button>
    </form>
{% endblock %}